apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: failure-model-pipeline-deployer
  namespace: mlops-poc
rules:
  - apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
    resourceNames:
      - failure-model
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: failure-model-pipeline-deployer
  namespace: mlops-poc
subjects:
  - kind: ServiceAccount
    name: pipeline-runner
    namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: failure-model-pipeline-deployer
