apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-mlops-poc-routes-to-prometheus
  namespace: monitoring
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: mlops-poc
  to:
    - group: ""
      kind: Service
      name: prometheus-server
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
  namespace: mlops-poc
spec:
  parentRefs:
    - name: mlops-poc-gateway
  hostnames:
    - prometheus.mlops.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-server
          namespace: monitoring
          port: 80
          weight: 100
